[package]
name = "mblocks"
version = "0.2.0"
edition = "2021"

[dependencies]
libc = "0.2"
x11 = "2.20.0"
concat-string = "1.0.1"
psutil = "3.2.2"
chrono = "0.4"
threadpool = "1.8.1"
lazy_static = "1.4.0"
